"""Stage 3.20 — CV_SECONDARY_STRUCTURE acceptance tests.

CV = Σ_windows s(RMSD_w),  s(x) = (1-x^6)/(1-x^12), x = RMSD/r0

Window = 30 backbone atoms (5 per residue: N,CA,CB,C,O; 6 residues).
Templates derived from Engh & Huber (1991) bond geometry and Pauling & Corey (1951)
backbone dihedrals using the NERF algorithm (Parsons 2005).
Translation-only (TYPE=SIMPLE) RMSD: center both window and template.

Subtypes:
  0 = alpha helix:  stride=5 (one residue), numWindows = N/5 − 5
  1 = antibeta:     stride=30, numWindows = N/30
  2 = parabeta:     stride=30, numWindows = N/30; min of two templates

API:
  atoms  = backbone atom list (5 per residue × all residues)
  params = [subtype, r0]
"""

import sys, math, random
import openmm as mm
import gluedplugin as gp

TOL_CV = 1e-4
TOL_F  = 1e-3

# Backbone templates — pre-centered, nm.
# Derived from Engh & Huber (1991) Acta Cryst. A47:392 ideal bond geometry
# and Pauling & Corey (1951) backbone dihedral angles, via NERF algorithm
# (Parsons et al. 2005 J. Comput. Chem. 26:1063).
# Generated by tools/gen_secstr_templates.py.
ALPHA_TEMPLATE = [
    [-0.296458, -0.401214, -0.210973],
    [-0.150658, -0.401214, -0.210973],
    [-0.097391, -0.472448, -0.334354],
    [-0.095510, -0.259035, -0.210973],
    [-0.005629, -0.226399, -0.133767],
    [-0.150113, -0.174920, -0.298184],
    [-0.106516, -0.036167, -0.308404],
    [-0.190650,  0.038711, -0.410625],
    [-0.119637,  0.035762, -0.174574],
    [-0.027661,  0.104531, -0.130809],
    [-0.234697,  0.019284, -0.110137],
    [-0.260076,  0.082562,  0.018741],
    [-0.396021,  0.040845,  0.072713],
    [-0.154352,  0.043111,  0.121319],
    [-0.100415,  0.128013,  0.191937],
    [-0.125318, -0.086361,  0.128833],
    [-0.026069, -0.137298,  0.222709],
    [-0.007769, -0.287221,  0.204741],
    [ 0.109286, -0.070287,  0.201617],
    [ 0.173494, -0.026764,  0.296946],
    [ 0.151930, -0.062432,  0.075990],
    [ 0.279636, -0.000760,  0.042147],
    [ 0.299600,  0.001091, -0.108625],
    [ 0.286513,  0.143018,  0.092514],
    [ 0.385421,  0.183861,  0.152957],
    [ 0.180638,  0.219221,  0.067096],
    [ 0.174465,  0.358497,  0.109778],
    [ 0.039642,  0.419209,  0.074122],
    [ 0.193480,  0.370855,  0.260583],
    [ 0.270836,  0.453949,  0.307657],
]
ANTIBETA_TEMPLATE = [
    [-0.425640, -0.251248, -0.266352],
    [-0.279840, -0.251248, -0.266352],
    [-0.226574, -0.322481, -0.389733],
    [-0.224693, -0.109068, -0.266352],
    [-0.271530, -0.023403, -0.340999],
    [-0.124861, -0.084855, -0.182033],
    [-0.063166,  0.046879, -0.172151],
    [-0.115927,  0.121419, -0.050519],
    [ 0.088359,  0.035953, -0.158845],
    [ 0.139075, -0.045405, -0.081949],
    [ 0.160002,  0.118559, -0.234384],
    [ 0.305766,  0.118334, -0.231173],
    [ 0.361565,  0.042782, -0.350809],
    [ 0.361228,  0.260343, -0.234884],
    [ 0.316237,  0.343440, -0.313467],
    [-0.160002,  0.118559,  0.237616],
    [-0.305766,  0.118334,  0.240827],
    [-0.361565,  0.042782,  0.121191],
    [-0.361228,  0.260343,  0.237116],
    [-0.316237,  0.343440,  0.158533],
    [ 0.124861, -0.084855,  0.289967],
    [ 0.063166,  0.046879,  0.299849],
    [ 0.115927,  0.121419,  0.421481],
    [-0.088359,  0.035953,  0.313155],
    [-0.139075, -0.045405,  0.390051],
    [ 0.425640, -0.251248,  0.205648],
    [ 0.279840, -0.251248,  0.205648],
    [ 0.226574, -0.322481,  0.082267],
    [ 0.224693, -0.109068,  0.205648],
    [ 0.271530, -0.023403,  0.131001],
]
PARABETA_TEMPLATE1 = [
    [-0.404229, -0.251661, -0.285656],
    [-0.258429, -0.251661, -0.285656],
    [-0.205163, -0.322895, -0.409037],
    [-0.203282, -0.109482, -0.285656],
    [-0.218981, -0.035894, -0.382830],
    [-0.138623, -0.071626, -0.175890],
    [-0.081050,  0.061707, -0.163026],
    [-0.140756,  0.134192, -0.043379],
    [ 0.070052,  0.054890, -0.143591],
    [ 0.118230,  0.007037, -0.041154],
    [ 0.144204,  0.103144, -0.242765],
    [ 0.289880,  0.102619, -0.236768],
    [ 0.347698,  0.023593, -0.353157],
    [ 0.345858,  0.244319, -0.243392],
    [ 0.334593,  0.311720, -0.345542],
    [-0.404229, -0.251661,  0.199344],
    [-0.258429, -0.251661,  0.199344],
    [-0.205163, -0.322895,  0.075963],
    [-0.203282, -0.109482,  0.199344],
    [-0.218981, -0.035894,  0.102170],
    [-0.138623, -0.071626,  0.309110],
    [-0.081050,  0.061707,  0.321974],
    [-0.140756,  0.134192,  0.441621],
    [ 0.070052,  0.054890,  0.341409],
    [ 0.118230,  0.007037,  0.443846],
    [ 0.144204,  0.103144,  0.242235],
    [ 0.289880,  0.102619,  0.248232],
    [ 0.347698,  0.023593,  0.131843],
    [ 0.345858,  0.244319,  0.241608],
    [ 0.334593,  0.311720,  0.139458],
]
PARABETA_TEMPLATE2 = [
    [-0.574229, -0.251661, -0.285656],
    [-0.428429, -0.251661, -0.285656],
    [-0.375163, -0.322895, -0.409037],
    [-0.373282, -0.109482, -0.285656],
    [-0.388981, -0.035894, -0.382830],
    [-0.308623, -0.071626, -0.175890],
    [-0.251050,  0.061707, -0.163026],
    [-0.310756,  0.134192, -0.043379],
    [-0.099948,  0.054890, -0.143591],
    [-0.051770,  0.007037, -0.041154],
    [-0.025796,  0.103144, -0.242765],
    [ 0.119880,  0.102619, -0.236768],
    [ 0.177698,  0.023593, -0.353157],
    [ 0.175858,  0.244319, -0.243392],
    [ 0.164593,  0.311720, -0.345542],
    [-0.234229, -0.251661,  0.199344],
    [-0.088429, -0.251661,  0.199344],
    [-0.035163, -0.322895,  0.075963],
    [-0.033282, -0.109482,  0.199344],
    [-0.048981, -0.035894,  0.102170],
    [ 0.031377, -0.071626,  0.309110],
    [ 0.088950,  0.061707,  0.321974],
    [ 0.029244,  0.134192,  0.441621],
    [ 0.240052,  0.054890,  0.341409],
    [ 0.288230,  0.007037,  0.443846],
    [ 0.314204,  0.103144,  0.242235],
    [ 0.459880,  0.102619,  0.248232],
    [ 0.517698,  0.023593,  0.131843],
    [ 0.515858,  0.244319,  0.241608],
    [ 0.504593,  0.311720,  0.139458],
]
TEMPLATES_BY_SUBTYPE = {0: [ALPHA_TEMPLATE], 1: [ANTIBETA_TEMPLATE],
                         2: [PARABETA_TEMPLATE1, PARABETA_TEMPLATE2]}


def get_cuda_platform():
    try:
        return mm.Platform.getPlatformByName("CUDA")
    except mm.OpenMMException:
        return None


def _switching(rmsd, r0):
    if rmsd < 1e-6:
        return 1.0
    x = rmsd / r0
    if x >= 0.9999:
        return 0.0
    x6 = x**6
    return (1.0 - x6) / (1.0 - x6 * x6)


def _window_rmsd(positions_win, template):
    """Translation-only RMSD: center both, then sqrt(mean |d|^2)."""
    n = len(template)
    cx = sum(positions_win[k][0] for k in range(n)) / n
    cy = sum(positions_win[k][1] for k in range(n)) / n
    cz = sum(positions_win[k][2] for k in range(n)) / n
    msd = 0.0
    for k in range(n):
        dx = positions_win[k][0] - cx - template[k][0]
        dy = positions_win[k][1] - cy - template[k][1]
        dz = positions_win[k][2] - cz - template[k][2]
        msd += dx*dx + dy*dy + dz*dz
    return math.sqrt(msd / n)


def _compute_cv_reference(positions, atoms, subtype, r0):
    """Python reference for one CV value (30-atom backbone windows)."""
    N = len(atoms)
    stride = 5 if subtype == 0 else 30
    num_windows = (N // 5 - 5) if subtype == 0 else (N // 30)
    templates = TEMPLATES_BY_SUBTYPE[subtype]
    cv = 0.0
    for w in range(num_windows):
        wStart = w * stride
        pts = [positions[atoms[wStart + k]] for k in range(30)]
        if subtype == 2:
            rmsd1 = _window_rmsd(pts, templates[0])
            rmsd2 = _window_rmsd(pts, templates[1])
            rmsd = min(rmsd1, rmsd2)
        else:
            rmsd = _window_rmsd(pts, templates[0])
        cv += _switching(rmsd, r0)
    return cv


def _make_ctx(positions, atom_list, subtype, r0, platform, bias_grad=0.0):
    n_atoms = len(positions)
    sys = mm.System()
    for _ in range(n_atoms):
        sys.addParticle(12.0)
    f = gp.GluedForce()
    f.setUsesPeriodicBoundaryConditions(False)
    av = mm.vectori()
    for a in atom_list:
        av.append(a)
    f.addCollectiveVariable(gp.GluedForce.CV_SECONDARY_STRUCTURE, av,
                            mm.vectord([float(subtype), r0]))
    f.setTestBiasGradients(mm.vectord([bias_grad]))
    sys.addForce(f)
    ctx = mm.Context(sys, mm.VerletIntegrator(0.001), platform)
    ctx.setPositions(positions)
    ctx.getState(getForces=True)
    return ctx, f


def test_perfect_alpha_single_window(platform):
    """CV=1 when 30 atoms exactly match centered alpha template (any translation)."""
    offset = [0.5, 0.3, 0.2]
    positions = [[t[k] + offset[k] for k in range(3)] for t in ALPHA_TEMPLATE]
    positions += [[0.0]*3]  # spare atom

    ctx, f = _make_ctx(positions, list(range(30)), 0, 0.08, platform)
    cvs = f.getLastCVValues(ctx)
    assert abs(cvs[0] - 1.0) < TOL_CV, \
        f"perfect alpha: expected CV=1.0, got {cvs[0]:.6f}"
    print(f"  test_perfect_alpha_single_window: OK  (cv={cvs[0]:.8f})")


def test_cv_value_alpha(platform):
    """CV matches Python reference for alpha subtype (2 windows = 40 backbone atoms)."""
    rng = random.Random(42)
    # 7 residues = 35 backbone atoms → numWindows = 35/5-5 = 7-5 = 2 windows
    N_res = 7
    N = N_res * 5  # 35 backbone atoms
    r0 = 0.08
    offset = [0.5, 0.5, 0.5]
    # Repeat the 30-atom template pattern, cycling through atoms
    positions = [[ALPHA_TEMPLATE[i % 30][k] + offset[k] + rng.uniform(-0.02, 0.02)
                  for k in range(3)] for i in range(N)]
    positions += [[0.0]*3]
    atom_list = list(range(N))

    ctx, f = _make_ctx(positions, atom_list, 0, r0, platform)
    cvs = f.getLastCVValues(ctx)
    ref = _compute_cv_reference(positions, atom_list, 0, r0)
    assert abs(cvs[0] - ref) < TOL_CV, \
        f"alpha cv: expected {ref:.6f}, got {cvs[0]:.6f}"
    print(f"  test_cv_value_alpha: OK  (cv={cvs[0]:.6f}, ref={ref:.6f})")


def test_cv_value_antibeta(platform):
    """CV matches Python reference for antibeta subtype (1 window = 30 atoms)."""
    rng = random.Random(7)
    N = 30  # 1 window
    r0 = 0.12
    positions = [[rng.uniform(-0.4, 0.4) for _ in range(3)] for _ in range(N)]
    positions += [[0.0]*3]
    atom_list = list(range(N))

    ctx, f = _make_ctx(positions, atom_list, 1, r0, platform)
    cvs = f.getLastCVValues(ctx)
    ref = _compute_cv_reference(positions, atom_list, 1, r0)
    assert abs(cvs[0] - ref) < TOL_CV, \
        f"antibeta cv: expected {ref:.6f}, got {cvs[0]:.6f}"
    print(f"  test_cv_value_antibeta: OK  (cv={cvs[0]:.6f}, ref={ref:.6f})")


def test_cv_value_parabeta(platform):
    """CV matches Python reference for parabeta subtype (1 window, 2 templates)."""
    rng = random.Random(13)
    N = 30  # 1 window
    r0 = 0.12
    positions = [[rng.uniform(-0.4, 0.4) for _ in range(3)] for _ in range(N)]
    positions += [[0.0]*3]
    atom_list = list(range(N))

    ctx, f = _make_ctx(positions, atom_list, 2, r0, platform)
    cvs = f.getLastCVValues(ctx)
    ref = _compute_cv_reference(positions, atom_list, 2, r0)
    assert abs(cvs[0] - ref) < TOL_CV, \
        f"parabeta cv: expected {ref:.6f}, got {cvs[0]:.6f}"
    print(f"  test_cv_value_parabeta: OK  (cv={cvs[0]:.6f}, ref={ref:.6f})")


def test_switching_value(platform):
    """Switching function s(RMSD/r0) matches Python for a controllable RMSD."""
    # Scaled template: positions = scale * template (already centered → COM=0)
    # d_k = (scale-1)*t_k → MSD = (scale-1)^2 * (1/30)*Σ|t_k|^2
    r0 = 0.5
    scale = 0.7

    tmpl_msd = sum(sum(v**2 for v in t) for t in ALPHA_TEMPLATE) / 30.0
    expected_rmsd = abs(scale - 1.0) * math.sqrt(tmpl_msd)
    expected_s = _switching(expected_rmsd, r0)

    positions = [[ALPHA_TEMPLATE[i][k] * scale for k in range(3)] for i in range(30)]
    positions += [[0.0]*3]

    ctx, f = _make_ctx(positions, list(range(30)), 0, r0, platform)
    cvs = f.getLastCVValues(ctx)
    assert abs(cvs[0] - expected_s) < TOL_CV, \
        f"switching: expected {expected_s:.6f}, got {cvs[0]:.6f}  (rmsd={expected_rmsd:.4f})"
    print(f"  test_switching_value: OK  (cv={cvs[0]:.6f}, ref={expected_s:.6f})")


def test_force_direction(platform):
    """Force on atom k = jacFactor * dk (sign checked) for single alpha window."""
    rng = random.Random(99)
    N = 30
    r0 = 0.5
    noise = 0.05
    positions = [[ALPHA_TEMPLATE[k][c] + rng.uniform(-noise, noise)
                  for c in range(3)] for k in range(N)]
    positions += [[0.0]*3]
    atom_list = list(range(N))
    template = ALPHA_TEMPLATE

    ctx, f = _make_ctx(positions, atom_list, 0, r0, platform, bias_grad=1.0)
    state = ctx.getState(getForces=True)
    unit = mm.unit.kilojoules_per_mole / mm.unit.nanometer
    raw = state.getForces(asNumpy=False)

    # Python reference Jacobian
    pts = [positions[k] for k in range(N)]
    cx = sum(p[0] for p in pts) / N
    cy = sum(p[1] for p in pts) / N
    cz = sum(p[2] for p in pts) / N
    dx = [pts[k][0] - cx - template[k][0] for k in range(N)]
    dy = [pts[k][1] - cy - template[k][1] for k in range(N)]
    dz = [pts[k][2] - cz - template[k][2] for k in range(N)]
    msd = sum(dx[k]**2 + dy[k]**2 + dz[k]**2 for k in range(N)) / N
    rmsd = math.sqrt(msd)

    if rmsd < 1e-6 or rmsd / r0 >= 0.9999:
        jf = 0.0
    else:
        x = rmsd / r0
        x5 = x**5; x6 = x**6; x12 = x**12
        num = 1.0 - x6; den = 1.0 - x12
        dsdx = -6.0 * x5 * num**2 / den**2
        jf = dsdx / (r0 * N * rmsd)  # jacFactor denominator = N=30

    for k in range(N):
        got_x = raw[k][0].value_in_unit(unit)
        got_y = raw[k][1].value_in_unit(unit)
        got_z = raw[k][2].value_in_unit(unit)
        assert abs(got_x - (-jf * dx[k])) < TOL_F, \
            f"atom {k} x: expected {-jf*dx[k]:.4f}, got {got_x:.4f}"
        assert abs(got_y - (-jf * dy[k])) < TOL_F, \
            f"atom {k} y: expected {-jf*dy[k]:.4f}, got {got_y:.4f}"
        assert abs(got_z - (-jf * dz[k])) < TOL_F, \
            f"atom {k} z: expected {-jf*dz[k]:.4f}, got {got_z:.4f}"
    print(f"  test_force_direction: OK  (rmsd={rmsd:.4f}, jf={jf:.6f})")


def test_numerical_gradient(platform):
    """Finite-difference check of Jacobian for alpha helix (2 windows)."""
    rng = random.Random(55)
    # 7 residues = 35 atoms → 2 windows
    N_res = 7
    N = N_res * 5
    r0 = 0.5
    noise = 0.05
    positions = [[ALPHA_TEMPLATE[i % 30][c] + rng.uniform(-noise, noise)
                  for c in range(3)] for i in range(N)]
    positions += [[0.0]*3]
    atom_list = list(range(N))

    sys_obj = mm.System()
    for _ in range(N + 1):
        sys_obj.addParticle(12.0)
    f_cv = gp.GluedForce()
    f_cv.setUsesPeriodicBoundaryConditions(False)
    av = mm.vectori()
    for a in atom_list:
        av.append(a)
    f_cv.addCollectiveVariable(gp.GluedForce.CV_SECONDARY_STRUCTURE, av,
                               mm.vectord([0.0, r0]))
    f_cv.setTestBiasGradients(mm.vectord([1.0]))
    sys_obj.addForce(f_cv)
    ctx = mm.Context(sys_obj, mm.VerletIntegrator(0.001), platform)

    h = 1e-4
    max_err = 0.0
    unit = mm.unit.kilojoules_per_mole / mm.unit.nanometer

    for ai in range(N):
        for ci in range(3):
            pos_p = [list(p) for p in positions]
            pos_m = [list(p) for p in positions]
            pos_p[ai][ci] += h
            pos_m[ai][ci] -= h
            fd = (_compute_cv_reference(pos_p, atom_list, 0, r0) -
                  _compute_cv_reference(pos_m, atom_list, 0, r0)) / (2*h)

            ctx.setPositions(positions)
            state = ctx.getState(getForces=True)
            raw = state.getForces(asNumpy=False)
            f_anal = -raw[ai][ci].value_in_unit(unit)
            max_err = max(max_err, abs(fd - f_anal))

    assert max_err < TOL_F, f"max gradient error {max_err:.2e} > {TOL_F}"
    print(f"  test_numerical_gradient: OK  (max_err={max_err:.2e})")


def test_two_secondary_structure_cvs(platform):
    """Two independent SS CVs (alpha + antibeta) on the same system."""
    rng = random.Random(17)
    r0 = 0.1
    N = 30

    pos_alpha = [[rng.uniform(-0.3, 0.3) for _ in range(3)] for _ in range(N)]
    pos_beta  = [[rng.uniform(-0.3, 0.3) for _ in range(3)] for _ in range(N)]
    positions = pos_alpha + pos_beta + [[0.0]*3]
    atoms_alpha = list(range(N))
    atoms_beta  = list(range(N, 2*N))

    n_atoms = len(positions)
    sys = mm.System()
    for _ in range(n_atoms):
        sys.addParticle(12.0)
    force = gp.GluedForce()
    force.setUsesPeriodicBoundaryConditions(False)

    av0 = mm.vectori()
    for a in atoms_alpha: av0.append(a)
    av1 = mm.vectori()
    for a in atoms_beta: av1.append(a)
    force.addCollectiveVariable(gp.GluedForce.CV_SECONDARY_STRUCTURE, av0,
                                mm.vectord([0.0, r0]))
    force.addCollectiveVariable(gp.GluedForce.CV_SECONDARY_STRUCTURE, av1,
                                mm.vectord([1.0, r0]))
    force.setTestBiasGradients(mm.vectord([0.0, 0.0]))
    sys.addForce(force)
    ctx = mm.Context(sys, mm.VerletIntegrator(0.001), platform)
    ctx.setPositions(positions)
    ctx.getState(getForces=True)

    cvs = force.getLastCVValues(ctx)
    ref0 = _compute_cv_reference(positions, atoms_alpha, 0, r0)
    ref1 = _compute_cv_reference(positions, atoms_beta, 1, r0)
    assert abs(cvs[0] - ref0) < TOL_CV, f"CV0 mismatch: {cvs[0]:.6f} vs {ref0:.6f}"
    assert abs(cvs[1] - ref1) < TOL_CV, f"CV1 mismatch: {cvs[1]:.6f} vs {ref1:.6f}"
    print(f"  test_two_secondary_structure_cvs: OK  (cv0={cvs[0]:.4f}, cv1={cvs[1]:.4f})")


if __name__ == "__main__":
    plat = get_cuda_platform()
    if plat is None:
        print("CUDA platform not available — skipping CV_SECONDARY_STRUCTURE tests.")
        import sys; sys.exit(0)
    print("Stage 3.20 — CV_SECONDARY_STRUCTURE tests (CUDA platform):")
    test_perfect_alpha_single_window(plat)
    test_cv_value_alpha(plat)
    test_cv_value_antibeta(plat)
    test_cv_value_parabeta(plat)
    test_switching_value(plat)
    test_force_direction(plat)
    test_numerical_gradient(plat)
    test_two_secondary_structure_cvs(plat)
    print("All CV_SECONDARY_STRUCTURE tests passed.")
